smol = true
telemetry = false

[install]
saveTextLockfile = true
auto = "auto"
# These packages will bypass the 3-day minimum age requirement
minimumReleaseAgeExcludes = ["@types/bun", "typescript"]

[install.lockfile]
save = true
